[package]
name = "hist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# csv = "1.2.1"
serde = {version = "1.0.164", features = ["derive"]}
tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}
